print('Welcome! to Madlib')
name = input("Enter your name: ")
print('Hello ' + name + ' we are going to take a journey!')
adj = input('Type in a adjetive: ')
print('You are very ' + adj + ' to go through this!')
zoo = input("type in a noun. ")
print('Today I went to the zoo and saw a ' + zoo + '!')
print('I was almost attacked by that ' + zoo + '!')
noun1 = input('Enter in a noun.')
print('I should have brought my ' + noun1 + ' with me, dang it!')